development:
  adapter: postgresql
  encoding: unicode
  database: homework_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: homework_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: homework_production
  pool: 5
  username:
  password: